version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "GoSuccess-GmbH"
    labels:
      - "dependencies"
      - "composer"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group all patch updates into one PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Security updates should be in separate PRs
    allow:
      - dependency-type: "all"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GoSuccess-GmbH"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
